---
title: "5. Statsbomb Clustering Passes"
author: "Ekrem Bayar"
date: "25 05 2020"
output: html_document
---

# 1. Friends of Tracking: Getting Started with R + StatsBomb | Analyzing Squad Rotation & Clustering Passes

*Video:* https://www.youtube.com/watch?v=ilIIjqfstfQ&t=4021s


# 2. Packages
```{r message=FALSE, warning=FALSE}
library(plyr)
library(tidyverse)
library(magrittr)
library(parallel)
library(rjson)
```

# 3. Pitch 
```{r}
source(file = "Functions/Pitch for Statsbomb.R")
```


# 4. FA Women's Super League 2018/2019 All Matches

## 4.1. Matches
```{r}
match.files <- list.files(path="C:\\Users\\dell\\Desktop\\FoT\\open-data-master\\data\\matches",
                          full.names = TRUE,recursive = TRUE)

match.id <- mclapply(match.files, function(x){
  
  match.temp <- fromJSON(file=x)
  
  matches.df <- mclapply(match.temp, function(y){
    
    data.frame(t(unlist(y)), stringsAsFactors = FALSE)
    
  })
  
  bind_rows(matches.df)
  
}) %>% bind_rows() %>% 
  filter(competition.competition_id == 37,
         season.season_id == 4) %>% 
  arrange(match_week) %>% 
  pull(match_id)

rm(match.files)
```


## 4.2. Events
```{r}
event.files <- list.files(path="C:\\Users\\dell\\Desktop\\FoT\\open-data-master\\data\\events",
                          full.names = TRUE,recursive = TRUE)

wsl.1819.index <- which(unlist(str_extract_all(event.files, "\\(?[0-9]+\\)?")) %in% match.id)

rm(match.id)

wsl.1819.index
```


# 5. All Passes in the FA Women's Super League
```{r}
full.pass.df <- mclapply(event.files[wsl.1819.index], function(x){
  
  match_id <- data.frame(match_id = as.numeric(str_extract_all(x, "\\(?[0-9]+\\)?")[[1]]))
  
  temp <- fromJSON(file=x)
  
  pass.index <- which(sapply(temp,function(i) i$type$name)=="Pass")

  event <- mclapply(temp[pass.index], function(y){
    
    if(is.null(y$pass$end_location)){end_location <- NA_real_}else{end_location <- y$pass$end_location}
    if(is.null(y$pass$recipient$name)){receiver <- NA_character_}else{receiver <- y$pass$recipient$name}
    if(is.null(y$pass$length)){pass_length <- NA_real_}else{pass_length <- y$pass$length}
    if(is.null(y$pass$angle)){pass_angle <- NA_real_}else{pass_angle <- y$pass$angle}
    if(is.null(y$pass$body_part$name)){body_part <- NA_character_}else{body_part <- y$pass$body_part$name}
    
    data.frame(
      Possession.Team = y$possession_team$name, 
      Possession = y$possession,
      Passer = y$player$name,
      X.Pass = y$location[1],
      Y.Pass = y$location[2],
      Pass.Type = y$pass$height$name,
      Receiver = receiver,
      X.Receive = end_location[1],
      Y.Receive = end_location[2],
      Pass.Length = pass_length,
      Pass.Angle = pass_angle,
      Body.Part = body_part,
      
      stringsAsFactors = FALSE
    )
  }) %>% bind_rows()
  
  cbind(match_id, event)

}) %>% bind_rows()



# Cleaning
full.pass.df2 <- full.pass.df %>% 
  filter(Y.Receive <= 80) %>% #cleaning the data
  mutate(Y.Pass = 80 - Y.Pass, #changing the axis so that origin starts at the lower left corner
         Y.Receive = 80 - Y.Receive)
```


# 6. K-Means

```{r}
cl <- full.pass.df2 %>% select("Possession.Team","X.Pass","Y.Pass","X.Receive","Y.Receive")


#perform k-means on the dataset (removing the 1st column because we just need to use the last 4 columns in our analysis)
mc = mclapply(c(25,50,75), function(x,centers) kmeans(x, centers, iter.max=1000), x=cl[,-1])

cl$Cluster.25 <- mc[[1]]$cluster #created clusters using 25 clusters
cl$Cluster.50 <- mc[[2]]$cluster #created clusters using 50 clusters
cl$Cluster.75 <- mc[[3]]$cluster #created clusters using 75 clusters

cluster.50.summary <- cl %>% 
  group_by(Cluster.50) %>% 
  summarise(X.Pass = mean(X.Pass),Y.Pass = mean(Y.Pass),
            X.Receive = mean(X.Receive), Y.Receive = mean(Y.Receive),
            count = n()) #obtain for each cluster id, the average location of the pass

cluster.50.team.summary <- cl %>% 
  group_by(Cluster.50,Possession.Team) %>% 
  summarise(count = n()) #get a count per team

arsenal.clusters <- cluster.50.team.summary %>% 
  group_by(Cluster.50) %>% 
  mutate(z.score = (count - mean(count))/sd(count)) %>%
  filter(Possession.Team == "Arsenal WFC" & z.score >= 1.5) #identify which clusters that arsenal does more than 1.5 sd than the league average

```


# 7. Visualization 

> Buraları Erhan hoca ile birlikte incele videodan farklılıklar mevcut!

```{r}
pitch() + geom_segment(data=cluster.50.summary, aes(x=X.Pass,xend=X.Receive,
                                                  y=Y.Pass,yend=Y.Receive,color=count),size=1.5,arrow=arrow(length = unit(0.03, "npc"))) +
  geom_text(data=cluster.50.summary,aes(x=X.Pass,y=Y.Pass,label=Cluster.50))
```

```{r}

pitch() + geom_segment(data=cluster.50.summary, aes(x=X.Pass,xend=X.Receive,
                                                   y=Y.Pass,yend=Y.Receive),size=1.5,arrow=arrow(length = unit(0.03, "npc"))) +
        geom_segment(data=cluster.50.summary[which(cluster.50.summary$Cluster.50 %in% arsenal.clusters$Cluster.50),], aes(x=X.Pass,xend=X.Receive,
                                            y=Y.Pass,yend=Y.Receive),size=1.5,color="red",arrow=arrow(length = unit(0.03, "npc")))
```


```{r}
pitch() + geom_segment(data=cl[which(cl$Cluster.50==12 & cl$Possession.Team == "Arsenal WFC"),], aes(x=X.Pass,xend=X.Receive,
                                                  y=Y.Pass,yend=Y.Receive),size=1.5,arrow=arrow(length = unit(0.03, "npc")))

```
















